---
title: "Are You Macho Enough to be a Vegetarian?"
author: "Yingfei Jiang"
date: '2020-03-10'
output: html_document
---

When you stand in front of the meat freezers in a supermarket picking a nice slab of steak, do you ever think of the reason why you want to eat meat? Is it because that meat is delicious? Or is it because you think meat is good for your health? A group of psychologists’ findings will provide you with a new answer- that people sometimes consume meat to secure their gender identity.  
Historically, meat consumption has been connected to gender identity. You might still remember your high school history class about pre-historic societies. The white-beard harsh-looking historical teacher told you how men acted as hunters and women acted as gatherers at that time.  
Now this connection has been proved scientifically. Mr. Rothgerber and his co-workers at Bellarmine University, UK find that eating meat makes men feel like a “real man.” This is shown by a positive correspondence between men’s meat consumption and their self-identity of masculinity.  
First, Mr. Rothgerber shows us that men do like meat more than women. By studying 86 high school students, he finds that men’s meat consumption is higher than women, and there are more female vegetarians than male ones. When justifying their meat consumption, men are more unapologetic while women are not. The top three strategies for male are pro-meat, health justification and hierarchical justification. This means their main arguments are “meat is good in general,” “meat is keeping me healthy,” and “human is superior to animals.” However, for women, the top three methods are disassociating meat-eating from animal suffering, disconnecting meat from animal, and differentiating farm animals from household pets. They are avoiding the problem!  
Mr. Rothgerber thinks that these differences in justification strategy might be caused by the tradition that men refuse to show weakness. In stereotype gender image, men should be tough and restrained, and showing empathy on animal suffering would be considered as weak and sensitive. To prove this assumption, Mr. Rothgerber uses a widely accepted psychological tool to test the participants’ masculinity score and compares the score with their diets. The result for men is as expected: eating beef, chicken, pork, and fish all show positive relationships with masculinity, among which beef has the highest masculinity score; having a vegetarian diet shows a negative relationship with masculinity.   
Unfortunately, meat consumption is not very environmental-friendly. A study in 2012 found that a healthy vegetarian diet will generate 0.7 tons of carbon emission less than a regular one provided by a national guideline. With all these findings, it proves that the belief in masculinity is harming our environment.  
Attitude towards meat consumption is not the first time masculinity prevents men from being pro-environment. Another group at Utah State University studied the relationship between “being environmental” and “being feminine”. They found that when the name of a non-profit organization is Wilderness Rangers, they get more donations from men, compared to the name of Friends of Nature. Also, if men feel that their masculinity is secured before going to a grocery store (e.g., telling them that they “write like a man”), they are more likely to purchase environmental items during shopping.  
These studies are important not because they reveal the inner secrets of why some men are averse to environmental products and services, but because they provide us some guidelines for designing our green products and strategies in the future. We do not really have the time to wait for every man to find a resolution between becoming environmental-friendly and feeling masculine. Why not make pro-environment efforts more tough and rugged, so men feel less demasculinized?  
However, you can always ask an unapologetic meat-eater guy: “How much beef do you need to eat to feel like a man?”  
  
**References:**  
* Brough, Aaron R. et al. “The Green-Feminine Stereotype and Its Effect on Sustainable Consumption.” Journal of Consumer Research 43.4 (2016): 567–582. Journal of Consumer Research. Web.  
* Hallström, E., A. Carlsson-Kanyama, and P. Börjesson. “Environmental Impact of Dietary Change: A Systematic Review.” Journal of Cleaner Production 15 Mar. 2015: 1–11. Journal of Cleaner Production. Web.  
* Rothgerber, Hank. “Real Men Don’t Eat (Vegetable) Quiche: Masculinity and the Justification of Meat Consumption.” Psychology of Men and Masculinity 14.4 (2013): 363–375. Psychology of Men and Masculinity. Web.

